### ISSUE TITLE
filter support with XDG Desktop Portal backend

### ISSUE THREAD

**Issue by Be-ing** [PolyMeilex/rfd#42]
https://github.com/PolyMeilex/rfd/blob/e331eff49a95b095e2e82750af114cf0c81c3dfd/src/backend/xdg_desktop_portal.rs#L199

**Comment by bilelmoussaoui** [comment]
This was fixed in ashpd 0.3 btw

**Comment by ogoffart** [comment]
But it is still not supported for [OpenFileOptions](https://docs.rs/ashpd/0.3.2/ashpd/desktop/file_chooser/struct.OpenFileOptions.html)

**Comment by bilelmoussaoui** [comment]
> But it is still not supported for [OpenFileOptions](https://docs.rs/ashpd/0.3.2/ashpd/desktop/file_chooser/struct.OpenFileOptions.html)

That needs to be implemented in the portals themselves, so in https://github.com/flatpak/xdg-desktop-portal/. ashpd is just a rust wrapper for the dbus interfaces.

**Comment by bilelmoussaoui** [comment]
Issue was opened at https://github.com/flatpak/xdg-desktop-portal/issues/796, i will look into fixing it in the upcoming days

**Comment by bjorn** [comment]
Waiting on https://github.com/bilelmoussaoui/ashpd/pull/90 to get merged.

**Comment by bjorn** [comment]
The replacement PR https://github.com/bilelmoussaoui/ashpd/pull/173 was merged, so this is waiting on a new release of `ashpd` now.

**Comment by theRookieCoder** [comment]
https://docs.rs/ashpd/latest/ashpd/desktop/file_chooser/struct.OpenFileRequest.html#method.current_folder
Support for default directories has been added in `ashpd 0.7.0`

I'll try to create a PR for this since

**Comment by bjorn** [comment]
> Support for default directories has been added in `ashpd 0.7.0`

According to https://github.com/bilelmoussaoui/ashpd/releases `current_folder` support has been added to `OpenFile` in ashpd 0.6.8, just in case that is relevant in terms of compatibility.

Thanks for contributing to this functionality!

**Comment by theRookieCoder** [comment]
Hmm I can't compile `zbus_names 2.6.0` on linux because `zvariant::Str<'_>: From<Cow<'_, str>>`, is this a known issue? Also occurs with the `rfd 0.14.0` crates.io release, no problems on `0.13`

**Comment by theRookieCoder** [comment]
Doesn't seem to work. No errors or anything, the picker just doesn't open the given directory.

![image](https://github.com/PolyMeilex/rfd/assets/60034030/2c136e23-a6c7-4483-b38d-f28e01cebdc7)

**Comment by bilelmoussaoui** [comment]
> Doesn't seem to work. No errors or anything, the picker just doesn't open the given directory.
> 
> ![image](https://private-user-images.githubusercontent.com/60034030/306527497-2c136e23-a6c7-4483-b38d-f28e01cebdc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTk2NTksIm5iZiI6MTcwODQ5OTM1OSwicGF0aCI6Ii82MDAzNDAzMC8zMDY1Mjc0OTctMmMxMzZlMjMtYTZjNy00NDgzLWIzOGQtZjI4ZTAxY2ViZGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA3MDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NzZlM2EyZTQ4ZjUxZTEzYzgwYjkwYjVhMTM1MmI2YTQ5OWJhYjJkMWFlNzM1NjkyNDViNWQ1ZDdkM2QwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ud4--BQ-Q8AsymMF5D_fzEFGIaYfOz_xYvATFdGBRow)
> 
> Edit: `FileDialog.save_file()` somehow still works despite using the same code

Sounds like a KDE portal implementation error/issue

**Comment by theRookieCoder** [comment]
Yup I can confirm it works on GNOME. Although it's weird that the save file works properly cos that means it's only partially implemented.

**Comment by mibuthu** [comment]
Would be great to get a new version with this fix, as it currently is a regression when running rfd version 0.14.0 with default features:

- with versions < 0.14.0 the the `set_directory` function is working correctly
- with version 0.14.0 the `set_directory` function is not working
- with master the `set_directory` function is working correctly again

**Comment by jangler** [comment]
i'm confused about the status of this issue. The docs currently say that `set_directory` is GTK-only on Linux, and links to this issue. But this issue is closed, and the last comment says that it works on master as of a year ago. But using version 0.15.0, this doesn't work for me in my Linux environments (KDE, LXQt).

**Comment by PolyMeilex** [comment]
The status is that docs are outdated
