### ISSUE TITLE
The `winit-example` doesn't compile

### ISSUE THREAD

**Issue by ManevilleF** [PolyMeilex/rfd#83]
The example doesn't compile in both native and `WASM`.

I'm using `rfd` 0.10

**Comment by PolyMeilex** [comment]
Fixed, thanks!

**Comment by ManevilleF** [comment]
Great !  but It's still not compiling in wasm, and the `wasm_build.sh` is not executable (`chmod +x ./wasm_build.sh` does the tric)

**Comment by PolyMeilex** [comment]
Fixed in #84
